project:
  type: website
  resources: 
    - plots/**
  output-dir: docs
  render: # Renderizar todos los archivos .qmd
    - home.qmd
    - dashboard.qmd
    - comprension_negocio.qmd
    - comprension_datos.qmd
    - preparacion.qmd
    - modelado.qmd
    - despliegue.qmd
    - documentacion.qmd

website:
  favicon: favicon.png
  navbar:
    logo: ctlogo.png
    left:
      - href: home.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard 
      - href: documentacion.qmd
        text: Documentaci√≥n
      
  back-to-top-navigation: true
      
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    execute:
      echo: false